name: speed_up_flutter
description: This package will speed up your developing.
version: 0.8.5
homepage: https://github.com/AndrewPiterov/speed_up_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter

  rxdart: ^0.27.5
  speed_up: ^0.8.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  given_when_then_unit_test: ^0.1.0
  lint: ^1.9.0
  shouldly: ^0.5.0+1
  
flutter:
