name: speed_up_flutter
description: This package will speed up your developing.
version: 0.5.5
homepage: https://github.com/AndrewPiterov/speed_up_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  speed_up: ^0.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  given_when_then_unit_test: ^0.0.4
  shouldly: ^0.2.4
  
    
flutter:
