name: speed_up_flutter
description: This package will speed up your developing.
version: 0.10.0
homepage: https://github.com/AndrewPiterov/speed_up_flutter

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  rxdart: ^0.28.0
  speed_up: ^0.9.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  given_when_then_unit_test: ^0.2.1
  lint: ^2.3.0
  shouldly: ^0.5.0+1 
