name: speed_up_flutter
description: This package will speed up your developing.
version: 0.8.9
homepage: https://github.com/AndrewPiterov/speed_up_flutter

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  rxdart: ^0.27.7
  speed_up: ^0.8.9

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  given_when_then_unit_test: ^0.2.1
  lint: ^2.1.2
  shouldly: ^0.5.0+1 
  
flutter:
